name: Branch Name
on:
  push:
    branches-ignore:
      - '[Cc][Cc][Oo][Ee]*'
      - 'main'
jobs:
  branch_name:
    runs-on: ubuntu-latest
    name: Branch Name
    steps:
      - name: Display the error message
        run: |
                echo "$GITHUB_REF"
