name: Branch Name
on:
  pull_request:
    branches:
      - main
jobs:
  branch_name:
    runs-on: ubuntu-latest
    name: Branch Name
    steps:
      - name: Display the error message
        run: |
                echo ${GITHUB_HEAD_REF}
                if [[ ${GITHUB_HEAD_REF} != *"CCoE"* ]]
                then
                  echo "ERROR: Incorrect branch name. Please amend branch name and try again. Correct branch name should start with JiraPro story number (CCOE or ccoe or CCoE)"
                  exit 1
                else
                  exit 0
                fi
