name: Branch Name
on:
  pull_request:
    branches:
      - main
jobs:
  branch_name:
    runs-on: ubuntu-latest
    name: Branch Name
    steps:
      - name: Display the error message
        run: |
                echo "$GITHUB_REF"
                if [[ $GITHUB_REF != "*CCOE*" ]]
                then
                  echo "ERROR: Incorrect branch name. Please amend branch name and try again. Correct branch name should start with JiraPro story number (CCOE or ccoe or CCoE)"
                  core.error
                fi
