name: CI
on: push
jobs:
  prod-check:
    if: ${{ github.ref != '/refs/head/[Cc][Cc][Oo][Ee]*' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to production server on branch $GITHUB_REF"
