name: Branch Name
on:
  push:
    branches-ignore:
      - '[C-c][C-c][O-o][E-e]*'
      - 'feature/[C-c][C-c][O-o][E-e]*'
      - 'fix/[C-c][C-c][O-o][E-e]*'
      - 'master'
      - 'main'
jobs:
  branch_name:
    runs-on: ubuntu-latest
    name: Branch Name
    steps:
      - name: Display the error message
        run: |
                echo "ERROR: Incorrect branch name. Please amend branch name and try again. Correct branch name should start with JiraPro story number (CCOE or ccoe or CCoE)"
                core.error
